version: "3.8"
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
        - USER=${USER:-laravel}
    ports:
      - "9000:9000"
    volumes:
      - ./backend:/var/www/html
      - .env:/var/www/html/.env
    networks:
      - app

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
        - USER=${USER:-laravel}
    restart: unless-stopped
    ports:
      - 8000:8000
    volumes:
      - ./backend:/var/www/html
      - ./nginx/conf.d/:/etc/nginx/conf.d/
      - .env:/var/www/html/.env
    depends_on:
      - backend
      - db
      - phpmyadmin
    networks:
      - app

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    tty: true
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/app/frontend
    depends_on:
      - backend
    networks:
      - app

  db:
    image: mariadb:10.6
    container_name: mysql
    restart: unless-stopped
    tty: true
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./database:/var/lib/mysql:rw
    networks:
      - app

  phpmyadmin:
    image: phpmyadmin:5.2.0
    container_name: phpmyadmin
    environment:
      PMA_ARBITRARY: 1
      PMA_HOST: ${DB_HOST}
      PMA_USER: ${DB_USERNAME}
      PMA_PASSWORD: ${DB_PASSWORD}
      PMA_PORT: ${DB_PORT}
    depends_on:
      - db
    ports:
      - 8888:80
    networks:
      - app

  laravel-migrate-seed:
    build:
      context: ./backend
      dockerfile: Dockerfile
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
        - USER=${USER:-laravel}
    container_name: laravel-migrate-seed
    volumes:
      - ./backend:/var/www/html
      - .env:/var/www/html/.env
    depends_on:
      - db
    profiles: ["migrate-seed"]
    working_dir: /var/www/html
    entrypoint: ["/bin/sh", "-c"]
    command:
      - |
        php artisan migrate
        php artisan db:seed
    networks:
      - app

  composer:
    build:
      context: ./backend
      dockerfile: Dockerfile
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
        - USER=${USER:-laravel}
    container_name: composer
    volumes:
      - ./backend:/var/www/html
      - .env:/var/www/html/.env
    working_dir: /var/www/html
    depends_on:
      - backend
    user: ${USER:-laravel} #system user
    profiles: ["composer"]
    entrypoint: ["composer", "--ignore-platform-reqs"]
    networks:
      - app

  artisan:
    build:
      context: ./backend
      dockerfile: Dockerfile
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
        - USER=${USER:-laravel}
    container_name: artisan
    volumes:
      - ./backend:/var/www/html
      - .env:/var/www/html/.env
    depends_on:
      - db
    working_dir: /var/www/html
    profiles: ["artisan"]
    entrypoint: ["php", "/var/www/html/artisan"]
    networks:
      - app

networks:
  app:
    driver: bridge
