const types = {
  SET_LOGEDIN: "SET_LOGIN/login",
  SET_LOGEDOUT: "SET_LOGIN/logout",

  USER_LOGIN_FETCH: "USER_LOGIN/fetch",
  USER_LOGIN_SUCCESS: "USER_LOGIN/success",
  USER_LOGIN_ERROR: "USER_LOGIN/error",

  REGISTER_FETCH: "REGISTER/fetch",
  REGISTER_SUCCESS: "REGISTER/success",
  REGISTER_ERROR: "REGISTER/error",

  PROFILE_FETCH: "PROFILE/fetch",
  PROFILE_DATA: "PROFILE/data",
  PROFILE_ERROR: "PROFILE/error",
  PROFILE_RESET: "PROFILE/reset",

  CATEGORIES_FETCH: "CATEGORIES/fetch",
  CATEGORIES_DATA: "CATEGORIES/data",
  CATEGORIES_ERROR: "CATEGORIES/error",
  CATEGORIES_RESET: "CATEGORIES/reset",

  SOURCES_FETCH: "SOURCES/fetch",
  SOURCES_DATA: "SOURCES/data",
  SOURCES_ERROR: "SOURCES/error",
  SOURCES_RESET: "SOURCES/reset",

  NEWS_FEED_FETCH: "NEWS_FEED/fetch",
  NEWS_FEED_DATA: "NEWS_FEED/data",
  NEWS_FEED_ERROR: "NEWS_FEED/error",
  NEWS_FEED_RESET: "NEWS_FEED/reset",
};
export default types;
